"""
explainability.py
-----------------
Data-driven explainability module for QDO allocation plans.
Produces clear, contextual explanations for why specific resource
allocations were generated for each emergency.
"""

from __future__ import annotations
import math
from typing import Dict, TYPE_CHECKING

if TYPE_CHECKING:
    from simulation.simulation import SimulationState
    from optimization.solver import AllocationPlan


def generate_allocation_explanations(
    plan: AllocationPlan,
    state: SimulationState,
) -> Dict[str, str]:
    """
    Generate data-driven explanations for each emergency allocation in an AllocationPlan.

    Parameters
    ----------
    plan : AllocationPlan
        The plan generated by a solver.
    state : SimulationState
        The simulation state containing emergency requirements and campus topology.

    Returns
    -------
    Dict[str, str]
        Mapping of emergency_id -> explanation text.
    """
    explanations: Dict[str, str] = {}
    depot = "main_gate"

    for em in state.active_emergencies:
        record = plan.allocations.get(em.id)
        if not record:
            explanations[em.id] = "No allocation recorded for this emergency."
            continue

        tt = state.travel_time(depot, em.location_id)
        tt_str = f"{tt:.2f} min" if not math.isinf(tt) else "unreachable route"

        assigned_total = (
            record.ambulances_assigned
            + record.rescue_teams_assigned
            + record.medical_supplies_assigned
            + record.medical_personnel_assigned
        )
        required_total = (
            em.ambulances_required
            + em.rescue_teams_required
            + em.medical_supplies_required
            + em.medical_personnel_required
        )

        parts = []

        # 1. Priority & Severity Context
        if em.severity >= 8:
            parts.append(
                f"High severity ({em.severity}/10) and {em.people_affected} affected people increased priority."
            )
        elif em.severity >= 6:
            parts.append(
                f"Moderate severity ({em.severity}/10) with {em.people_affected} people affected."
            )
        else:
            parts.append(
                f"Lower severity ({em.severity}/10) with {em.people_affected} people affected."
            )

        # 2. Location & Travel Time Context
        if tt <= 1.5:
            parts.append(f"Depot proximity is very close ({tt_str} travel time).")
        elif tt <= 3.5:
            parts.append(f"Moderate travel time from depot ({tt_str}).")
        else:
            parts.append(f"Distant location from main gate ({tt_str} travel time).")

        # 3. Solver Optimization Rationale
        is_qubo = "QUBO" in plan.solver_name
        if assigned_total == required_total:
            if is_qubo:
                parts.append(
                    "QUBO selected full allocation to minimize combined response delay and unmet demand penalties."
                )
            else:
                parts.append(
                    "Greedy solver fully satisfied demand based on priority ranking."
                )
        elif assigned_total > 0:
            if is_qubo:
                parts.append(
                    "QUBO selected partial allocation to balance response time and demand satisfaction across competing emergencies under resource capacity constraints."
                )
            else:
                parts.append(
                    "Greedy solver assigned available capacity until resource pool was exhausted."
                )
        else:
            if is_qubo:
                parts.append(
                    "QUBO allocated zero resources to prioritize higher-severity/closer emergency demands."
                )
            else:
                parts.append(
                    "Demand remained completely unmet because available capacity was exhausted by higher-ranked emergencies."
                )

        # 4. Bottleneck Analysis
        unmet_details = []
        if record.ambulances_assigned < em.ambulances_required:
            unmet_details.append(
                f"ambulances ({record.ambulances_assigned}/{em.ambulances_required})"
            )
        if record.rescue_teams_assigned < em.rescue_teams_required:
            unmet_details.append(
                f"rescue teams ({record.rescue_teams_assigned}/{em.rescue_teams_required})"
            )
        if record.medical_supplies_assigned < em.medical_supplies_required:
            unmet_details.append(
                f"supplies ({record.medical_supplies_assigned}/{em.medical_supplies_required})"
            )
        if record.medical_personnel_assigned < em.medical_personnel_required:
            unmet_details.append(
                f"personnel ({record.medical_personnel_assigned}/{em.medical_personnel_required})"
            )

        if unmet_details:
            parts.append(f"Shortfall in: {', '.join(unmet_details)}.")

        explanations[em.id] = " ".join(parts)

    return explanations
